model:
  name: ChatGPT
  parameters:
    model_name: gpt-4o-mini
prompts:
  non_leaf_prompt_path: prompts/non_leaf_classification.txt
  leaf_prompt_path: prompts/azadea/default_prompt_leaf.txt
  note: prompts/note.txt
inference:
  level: presets                  # level can be 'attribute', 'category' and 'presets'
  text_cols: name
  image_cols: image_link