model:
  name: FashionAPI
  parameters:
    max_new_tokens: 64
prompts:
  non_leaf_prompt_path: prompts/non_leaf_classification.txt
  leaf_prompt_path: prompts/leaf_classification_attribute.txt
  note: prompts/note.txt
inference:
  level: attribute # level can be 'attribute', 'category' and 'presets'
  text_cols: []
  image_cols: []