model:
  name: TaxonomyLookup
  parameters:
    # max_new_tokens: 64
    # model_name: gpt-4o-mini
    word_dict:
      red: red, reddish, redd
      yellow: yellowish, yell, yellow
    return_type: single
prompts:
  non_leaf_prompt_path: prompts/non_leaf_classification.txt
  leaf_prompt_path: prompts/leaf_classification_attribute.txt
  note: prompts/note.txt
inference:
  level: attribute # level can be 'attribute', 'category' and 'presets'